version: '3.8'

services:
  redis:
    container_name: beria_redis
    ports:
      - 6380:6379 # только для GUI базы

  server:
    container_name: beria_server
    environment:
      - APP_PORT=80
      - REDIS_HOST
      - REDIS_PORT

  nginx:
    container_name: beria_nginx
    build: ./nginx
