version: '3.8'

services:
  redis:
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/app/redis.conf
      - ./redis/city_data:/app/city_data

  server:
    restart: unless-stopped
    volumes:
      - ./server:/app
    environment:
      - IS_DEV=true

  nginx:
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/beria_nginx.conf:/etc/nginx/conf.d/beria_nginx.conf
    ports:
      - 81:80
