version: '3.8'

services:
  redis:
    container_name: beria_redis
    build: ./redis
    ports:
      - 6380:6379 # только для GUI базы

  server:
    container_name: beria_server
    build: ./server
    environment:
      - REDIS_HOST
      - REDIS_PASS
      - REDIS_PORT

  nginx:
    container_name: beria_nginx
    build: ./nginx
